[build-system]
requires = ["meson-python>=0.13.1", "pybind11>=2.11.0", "numpy>=2.0.0"]
build-backend = "mesonpy"

[project]
name = "gaara"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = ["numpy", "osteoid"]
authors = [
    { name = "William Silversmith", email = "ws9@princeton.edu" }
]
description = "Skeleton generation via 3D voxel thinning."
readme = "README.md"
license = "BSD-3-Clause"
classifiers = [
    "Intended Audience :: Developers",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Topic :: Utilities",
]

[project.optional-dependencies]
big = ["crackle-codec", "fill_voids", "psutil", "tqdm"]

[project.urls]
Homepage = "https://github.com/seung-lab/gaara/"
Repository = "https://github.com/seung-lab/gaara/"
"Bug Tracker" = "https://github.com/seung-lab/gaara/issues"